export const countries = [
    { name: 'Afghanistan', code: 'AF', dateFormat: 'dd / MM / yyyy' },
    { name: 'Åland Islands', code: 'AX', dateFormat: 'dd / MM / yyyy' },
    { name: 'Albania', code: 'AL', dateFormat: 'dd / MM / yyyy' },
    { name: 'Algeria', code: 'DZ', dateFormat: 'dd / MM / yyyy' },
    { name: 'American Samoa', code: 'AS', dateFormat: 'dd / MM / yyyy' },
    { name: 'Andorra', code: 'AD', dateFormat: 'dd / MM / yyyy' },
    { name: 'Angola', code: 'AO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Anguilla', code: 'AI', dateFormat: 'dd / MM / yyyy' },
    { name: 'Antarctica', code: 'AQ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Antigua and Barbuda', code: 'AG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Argentina', code: 'AR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Armenia', code: 'AM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Aruba', code: 'AW', dateFormat: 'dd / MM / yyyy' },
    { name: 'Australia', code: 'AU', dateFormat: 'dd / MM / yyyy' },
    { name: 'Austria', code: 'AT', dateFormat: 'dd / MM / yyyy' },
    { name: 'Azerbaijan', code: 'AZ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Bahamas', code: 'BS', dateFormat: 'dd / MM / yyyy' },
    { name: 'Bahrain', code: 'BH', dateFormat: 'dd / MM / yyyy' },
    { name: 'Bangladesh', code: 'BD', dateFormat: 'dd / MM / yyyy' },
    { name: 'Barbados', code: 'BB', dateFormat: 'dd / MM / yyyy' },
    { name: 'Belarus', code: 'BY', dateFormat: 'dd / MM / yyyy' },
    { name: 'Belgium', code: 'BE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Belize', code: 'BZ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Benin', code: 'BJ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Bermuda', code: 'BM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Bhutan', code: 'BT', dateFormat: 'dd / MM / yyyy' },
    { name: 'Bolivia (Plurinational State of)', code: 'BO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Bonaire, Sint Eustatius and Saba', code: 'BQ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Bosnia and Herzegovina', code: 'BA', dateFormat: 'dd / MM / yyyy' },
    { name: 'Botswana', code: 'BW', dateFormat: 'dd / MM / yyyy' },
    { name: 'Bouvet Island', code: 'BV', dateFormat: 'dd / MM / yyyy' },
    { name: 'Brazil', code: 'BR', dateFormat: 'dd / MM / yyyy' },
    { name: 'British Indian Ocean Territory', code: 'IO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Brunei Darussalam', code: 'BN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Bulgaria', code: 'BG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Burkina Faso', code: 'BF', dateFormat: 'dd / MM / yyyy' },
    { name: 'Burundi', code: 'BI', dateFormat: 'dd / MM / yyyy' },
    { name: 'Cabo Verde', code: 'CV', dateFormat: 'dd / MM / yyyy' },
    { name: 'Cambodia', code: 'KH', dateFormat: 'dd / MM / yyyy' },
    { name: 'Cameroon', code: 'CM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Canada', code: 'CA', dateFormat: 'dd / MM / yyyy' },
    { name: 'Cayman Islands', code: 'KY', dateFormat: 'dd / MM / yyyy' },
    { name: 'Central African Republic', code: 'CF', dateFormat: 'dd / MM / yyyy' },
    { name: 'Chad', code: 'TD', dateFormat: 'dd / MM / yyyy' },
    { name: 'Chile', code: 'CL', dateFormat: 'dd / MM / yyyy' },
    { name: 'China', code: 'CN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Christmas Island', code: 'CX', dateFormat: 'dd / MM / yyyy' },
    { name: 'Cocos (Keeling) Islands', code: 'CC', dateFormat: 'dd / MM / yyyy' },
    { name: 'Colombia', code: 'CO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Comoros', code: 'KM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Congo', code: 'CG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Congo, Democratic Republic of the', code: 'CD', dateFormat: 'dd / MM / yyyy' },
    { name: 'Cook Islands', code: 'CK', dateFormat: 'dd / MM / yyyy' },
    { name: 'Costa Rica', code: 'CR', dateFormat: 'dd / MM / yyyy' },
    { name: "Côte d'Ivoire", code: 'CI', dateFormat: 'dd / MM / yyyy' },
    { name: 'Croatia', code: 'HR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Cuba', code: 'CU', dateFormat: 'dd / MM / yyyy' },
    { name: 'Curaçao', code: 'CW', dateFormat: 'dd / MM / yyyy' },
    { name: 'Cyprus', code: 'CY', dateFormat: 'dd / MM / yyyy' },
    { name: 'Czechia', code: 'CZ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Denmark', code: 'DK', dateFormat: 'dd / MM / yyyy' },
    { name: 'Djibouti', code: 'DJ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Dominica', code: 'DM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Dominican Republic', code: 'DO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Ecuador', code: 'EC', dateFormat: 'dd / MM / yyyy' },
    { name: 'Egypt', code: 'EG', dateFormat: 'dd / MM / yyyy' },
    { name: 'El Salvador', code: 'SV', dateFormat: 'dd / MM / yyyy' },
    { name: 'Equatorial Guinea', code: 'GQ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Eritrea', code: 'ER', dateFormat: 'dd / MM / yyyy' },
    { name: 'Estonia', code: 'EE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Eswatini', code: 'SZ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Ethiopia', code: 'ET', dateFormat: 'dd / MM / yyyy' },
    { name: 'Falkland Islands (Malvinas)', code: 'FK', dateFormat: 'dd / MM / yyyy' },
    { name: 'Faroe Islands', code: 'FO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Fiji', code: 'FJ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Finland', code: 'FI', dateFormat: 'dd / MM / yyyy' },
    { name: 'France', code: 'FR', dateFormat: 'dd / MM / yyyy' },
    { name: 'French Guiana', code: 'GF', dateFormat: 'dd / MM / yyyy' },
    { name: 'French Polynesia', code: 'PF', dateFormat: 'dd / MM / yyyy' },
    { name: 'French Southern Territories', code: 'TF', dateFormat: 'dd / MM / yyyy' },
    { name: 'Gabon', code: 'GA', dateFormat: 'dd / MM / yyyy' },
    { name: 'Gambia', code: 'GM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Georgia', code: 'GE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Germany', code: 'DE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Ghana', code: 'GH', dateFormat: 'dd / MM / yyyy' },
    { name: 'Gibraltar', code: 'GI', dateFormat: 'dd / MM / yyyy' },
    { name: 'Greece', code: 'GR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Greenland', code: 'GL', dateFormat: 'dd / MM / yyyy' },
    { name: 'Grenada', code: 'GD', dateFormat: 'dd / MM / yyyy' },
    { name: 'Guadeloupe', code: 'GP', dateFormat: 'dd / MM / yyyy' },
    { name: 'Guam', code: 'GU', dateFormat: 'dd / MM / yyyy' },
    { name: 'Guatemala', code: 'GT', dateFormat: 'dd / MM / yyyy' },
    { name: 'Guernsey', code: 'GG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Guinea', code: 'GN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Guinea-Bissau', code: 'GW', dateFormat: 'dd / MM / yyyy' },
    { name: 'Guyana', code: 'GY', dateFormat: 'dd / MM / yyyy' },
    { name: 'Haiti', code: 'HT', dateFormat: 'dd / MM / yyyy' },
    { name: 'Heard Island and McDonald Islands', code: 'HM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Holy See', code: 'VA', dateFormat: 'dd / MM / yyyy' },
    { name: 'Honduras', code: 'HN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Hong Kong', code: 'HK', dateFormat: 'dd / MM / yyyy' },
    { name: 'Hungary', code: 'HU', dateFormat: 'dd / MM / yyyy' },
    { name: 'Iceland', code: 'IS', dateFormat: 'dd / MM / yyyy' },
    { name: 'India', code: 'IN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Indonesia', code: 'ID', dateFormat: 'dd / MM / yyyy' },
    { name: 'Iran (Islamic Republic of)', code: 'IR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Iraq', code: 'IQ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Ireland', code: 'IE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Isle of Man', code: 'IM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Israel', code: 'IL', dateFormat: 'dd / MM / yyyy' },
    { name: 'Italy', code: 'IT', dateFormat: 'dd / MM / yyyy' },
    { name: 'Jamaica', code: 'JM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Japan', code: 'JP', dateFormat: 'dd / MM / yyyy' },
    { name: 'Jersey', code: 'JE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Jordan', code: 'JO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Kazakhstan', code: 'KZ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Kenya', code: 'KE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Kiribati', code: 'KI', dateFormat: 'dd / MM / yyyy' },
    { name: "Korea (Democratic People's Republic of)", code: 'KP', dateFormat: 'dd / MM / yyyy' },
    { name: 'Korea, Republic of', code: 'KR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Kuwait', code: 'KW', dateFormat: 'dd / MM / yyyy' },
    { name: 'Kyrgyzstan', code: 'KG', dateFormat: 'dd / MM / yyyy' },
    { name: "Lao People's Democratic Republic", code: 'LA', dateFormat: 'dd / MM / yyyy' },
    { name: 'Latvia', code: 'LV', dateFormat: 'dd / MM / yyyy' },
    { name: 'Lebanon', code: 'LB', dateFormat: 'dd / MM / yyyy' },
    { name: 'Lesotho', code: 'LS', dateFormat: 'dd / MM / yyyy' },
    { name: 'Liberia', code: 'LR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Libya', code: 'LY', dateFormat: 'dd / MM / yyyy' },
    { name: 'Liechtenstein', code: 'LI', dateFormat: 'dd / MM / yyyy' },
    { name: 'Lithuania', code: 'LT', dateFormat: 'dd / MM / yyyy' },
    { name: 'Luxembourg', code: 'LU', dateFormat: 'dd / MM / yyyy' },
    { name: 'Macao', code: 'MO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Madagascar', code: 'MG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Malawi', code: 'MW', dateFormat: 'dd / MM / yyyy' },
    { name: 'Malaysia', code: 'MY', dateFormat: 'dd / MM / yyyy' },
    { name: 'Maldives', code: 'MV', dateFormat: 'dd / MM / yyyy' },
    { name: 'Mali', code: 'ML', dateFormat: 'dd / MM / yyyy' },
    { name: 'Malta', code: 'MT', dateFormat: 'dd / MM / yyyy' },
    { name: 'Marshall Islands', code: 'MH', dateFormat: 'dd / MM / yyyy' },
    { name: 'Martinique', code: 'MQ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Mauritania', code: 'MR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Mauritius', code: 'MU', dateFormat: 'dd / MM / yyyy' },
    { name: 'Mayotte', code: 'YT', dateFormat: 'dd / MM / yyyy' },
    { name: 'Mexico', code: 'MX', dateFormat: 'dd / MM / yyyy' },
    { name: 'Micronesia (Federated States of)', code: 'FM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Moldova, Republic of', code: 'MD', dateFormat: 'dd / MM / yyyy' },
    { name: 'Monaco', code: 'MC', dateFormat: 'dd / MM / yyyy' },
    { name: 'Mongolia', code: 'MN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Montenegro', code: 'ME', dateFormat: 'dd / MM / yyyy' },
    { name: 'Montserrat', code: 'MS', dateFormat: 'dd / MM / yyyy' },
    { name: 'Morocco', code: 'MA', dateFormat: 'dd / MM / yyyy' },
    { name: 'Mozambique', code: 'MZ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Myanmar', code: 'MM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Namibia', code: 'NA', dateFormat: 'dd / MM / yyyy' },
    { name: 'Nauru', code: 'NR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Nepal', code: 'NP', dateFormat: 'dd / MM / yyyy' },
    { name: 'Netherlands', code: 'NL', dateFormat: 'dd / MM / yyyy' },
    { name: 'New Caledonia', code: 'NC', dateFormat: 'dd / MM / yyyy' },
    { name: 'New Zealand', code: 'NZ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Nicaragua', code: 'NI', dateFormat: 'dd / MM / yyyy' },
    { name: 'Niger', code: 'NE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Nigeria', code: 'NG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Niue', code: 'NU', dateFormat: 'dd / MM / yyyy' },
    { name: 'Norfolk Island', code: 'NF', dateFormat: 'dd / MM / yyyy' },
    { name: 'North Macedonia', code: 'MK', dateFormat: 'dd / MM / yyyy' },
    { name: 'Northern Mariana Islands', code: 'MP', dateFormat: 'dd / MM / yyyy' },
    { name: 'Norway', code: 'NO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Oman', code: 'OM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Pakistan', code: 'PK', dateFormat: 'dd / MM / yyyy' },
    { name: 'Palau', code: 'PW', dateFormat: 'dd / MM / yyyy' },
    { name: 'Palestine, State of', code: 'PS', dateFormat: 'dd / MM / yyyy' },
    { name: 'Panama', code: 'PA', dateFormat: 'dd / MM / yyyy' },
    { name: 'Papua New Guinea', code: 'PG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Paraguay', code: 'PY', dateFormat: 'dd / MM / yyyy' },
    { name: 'Peru', code: 'PE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Philippines', code: 'PH', dateFormat: 'dd / MM / yyyy' },
    { name: 'Pitcairn', code: 'PN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Poland', code: 'PL', dateFormat: 'dd / MM / yyyy' },
    { name: 'Portugal', code: 'PT', dateFormat: 'dd / MM / yyyy' },
    { name: 'Puerto Rico', code: 'PR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Qatar', code: 'QA', dateFormat: 'dd / MM / yyyy' },
    { name: 'Réunion', code: 'RE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Romania', code: 'RO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Russian Federation', code: 'RU', dateFormat: 'dd / MM / yyyy' },
    { name: 'Rwanda', code: 'RW', dateFormat: 'dd / MM / yyyy' },
    { name: 'Saint Barthélemy', code: 'BL', dateFormat: 'dd / MM / yyyy' },
    {
        name: 'Saint Helena, Ascension and Tristan da Cunha',
        code: 'SH',
        dateFormat: 'dd / MM / yyyy',
    },
    { name: 'Saint Kitts and Nevis', code: 'KN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Saint Lucia', code: 'LC', dateFormat: 'dd / MM / yyyy' },
    { name: 'Saint Martin (French part)', code: 'MF', dateFormat: 'dd / MM / yyyy' },
    { name: 'Saint Pierre and Miquelon', code: 'PM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC', dateFormat: 'dd / MM / yyyy' },
    { name: 'Samoa', code: 'WS', dateFormat: 'dd / MM / yyyy' },
    { name: 'San Marino', code: 'SM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Sao Tome and Principe', code: 'ST', dateFormat: 'dd / MM / yyyy' },
    { name: 'Saudi Arabia', code: 'SA', dateFormat: 'dd / MM / yyyy' },
    { name: 'Senegal', code: 'SN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Serbia', code: 'RS', dateFormat: 'dd / MM / yyyy' },
    { name: 'Seychelles', code: 'SC', dateFormat: 'dd / MM / yyyy' },
    { name: 'Sierra Leone', code: 'SL', dateFormat: 'dd / MM / yyyy' },
    { name: 'Singapore', code: 'SG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Sint Maarten (Dutch part)', code: 'SX', dateFormat: 'dd / MM / yyyy' },
    { name: 'Slovakia', code: 'SK', dateFormat: 'dd / MM / yyyy' },
    { name: 'Slovenia', code: 'SI', dateFormat: 'dd / MM / yyyy' },
    { name: 'Solomon Islands', code: 'SB', dateFormat: 'dd / MM / yyyy' },
    { name: 'Somalia', code: 'SO', dateFormat: 'dd / MM / yyyy' },
    { name: 'South Africa', code: 'ZA', dateFormat: 'dd / MM / yyyy' },
    {
        name: 'South Georgia and the South Sandwich Islands',
        code: 'GS',
        dateFormat: 'dd / MM / yyyy',
    },
    { name: 'South Sudan', code: 'SS', dateFormat: 'dd / MM / yyyy' },
    { name: 'Spain', code: 'ES', dateFormat: 'dd / MM / yyyy' },
    { name: 'Sri Lanka', code: 'LK', dateFormat: 'dd / MM / yyyy' },
    { name: 'Sudan', code: 'SD', dateFormat: 'dd / MM / yyyy' },
    { name: 'Suriname', code: 'SR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Svalbard and Jan Mayen', code: 'SJ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Sweden', code: 'SE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Switzerland', code: 'CH', dateFormat: 'dd / MM / yyyy' },
    { name: 'Syrian Arab Republic', code: 'SY', dateFormat: 'dd / MM / yyyy' },
    { name: 'Taiwan, Province of China', code: 'TW', dateFormat: 'dd / MM / yyyy' },
    { name: 'Tajikistan', code: 'TJ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Tanzania, United Republic of', code: 'TZ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Thailand', code: 'TH', dateFormat: 'dd / MM / yyyy' },
    { name: 'Timor-Leste', code: 'TL', dateFormat: 'dd / MM / yyyy' },
    { name: 'Togo', code: 'TG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Tokelau', code: 'TK', dateFormat: 'dd / MM / yyyy' },
    { name: 'Tonga', code: 'TO', dateFormat: 'dd / MM / yyyy' },
    { name: 'Trinidad and Tobago', code: 'TT', dateFormat: 'dd / MM / yyyy' },
    { name: 'Tunisia', code: 'TN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Turkey', code: 'TR', dateFormat: 'dd / MM / yyyy' },
    { name: 'Turkmenistan', code: 'TM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Turks and Caicos Islands', code: 'TC', dateFormat: 'dd / MM / yyyy' },
    { name: 'Tuvalu', code: 'TV', dateFormat: 'dd / MM / yyyy' },
    { name: 'Uganda', code: 'UG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Ukraine', code: 'UA', dateFormat: 'dd / MM / yyyy' },
    { name: 'United Arab Emirates', code: 'AE', dateFormat: 'dd / MM / yyyy' },
    {
        name: 'United Kingdom of Great Britain and Northern Ireland',
        code: 'GB',
        dateFormat: 'dd / MM / yyyy',
    },
    { name: 'United States', code: 'US', dateFormat: 'MM / dd / yyyy' },
    { name: 'United States Minor Outlying Islands', code: 'UM', dateFormat: 'MM / dd / yyyy' },
    { name: 'Uruguay', code: 'UY', dateFormat: 'dd / MM / yyyy' },
    { name: 'Uzbekistan', code: 'UZ', dateFormat: 'dd / MM / yyyy' },
    { name: 'Vanuatu', code: 'VU', dateFormat: 'dd / MM / yyyy' },
    { name: 'Venezuela (Bolivarian Republic of)', code: 'VE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Viet Nam', code: 'VN', dateFormat: 'dd / MM / yyyy' },
    { name: 'Virgin Islands (British)', code: 'VG', dateFormat: 'dd / MM / yyyy' },
    { name: 'Virgin Islands (U.S.)', code: 'VI', dateFormat: 'MM / dd / yyyy' },
    { name: 'Wallis and Futuna', code: 'WF', dateFormat: 'dd / MM / yyyy' },
    { name: 'Western Sahara', code: 'EH', dateFormat: 'dd / MM / yyyy' },
    { name: 'Yemen', code: 'YE', dateFormat: 'dd / MM / yyyy' },
    { name: 'Zambia', code: 'ZM', dateFormat: 'dd / MM / yyyy' },
    { name: 'Zimbabwe', code: 'ZW', dateFormat: 'dd / MM / yyyy' },
]

export const states = [
    { name: 'Alabama', code: 'AL' },
    { name: 'Alaska', code: 'AK' },
    { name: 'Arizona', code: 'AZ' },
    { name: 'Arkansas', code: 'AR' },
    { name: 'California', code: 'CA' },
    { name: 'Colorado', code: 'CO' },
    { name: 'Connecticut', code: 'CT' },
    { name: 'Delaware', code: 'DE' },
    { name: 'District of Columbia', code: 'DC' },
    { name: 'Florida', code: 'FL' },
    { name: 'Georgia', code: 'GA' },
    { name: 'Hawaii', code: 'HI' },
    { name: 'Idaho', code: 'ID' },
    { name: 'Illinois', code: 'IL' },
    { name: 'Indiana', code: 'IN' },
    { name: 'Iowa', code: 'IA' },
    { name: 'Kansas', code: 'KS' },
    { name: 'Kentucky', code: 'KY' },
    { name: 'Louisiana', code: 'LA' },
    { name: 'Maine', code: 'ME' },
    { name: 'Maryland', code: 'MD' },
    { name: 'Massachusetts', code: 'MA' },
    { name: 'Michigan', code: 'MI' },
    { name: 'Minnesota', code: 'MN' },
    { name: 'Mississippi', code: 'MS' },
    { name: 'Missouri', code: 'MO' },
    { name: 'Montana', code: 'MT' },
    { name: 'Nebraska', code: 'NE' },
    { name: 'Nevada', code: 'NV' },
    { name: 'New Hampshire', code: 'NH' },
    { name: 'New Jersey', code: 'NJ' },
    { name: 'New Mexico', code: 'NM' },
    { name: 'New York', code: 'NY' },
    { name: 'North Carolina', code: 'NC' },
    { name: 'North Dakota', code: 'ND' },
    { name: 'Ohio', code: 'OH' },
    { name: 'Oklahoma', code: 'OK' },
    { name: 'Oregon', code: 'OR' },
    { name: 'Pennsylvania', code: 'PA' },
    { name: 'Rhode Island', code: 'RI' },
    { name: 'South Carolina', code: 'SC' },
    { name: 'South Dakota', code: 'SD' },
    { name: 'Tennessee', code: 'TN' },
    { name: 'Texas', code: 'TX' },
    { name: 'Utah', code: 'UT' },
    { name: 'Vermont', code: 'VT' },
    { name: 'Virginia', code: 'VA' },
    { name: 'Washington', code: 'WA' },
    { name: 'West Virginia', code: 'WV' },
    { name: 'Wisconsin', code: 'WI' },
    { name: 'Wyoming', code: 'WY' },
]
