import_market_data:
  cron: "0 22 * * 1-5" # 5:00 PM EST / 6:00 PM EDT (NY time)
  class: "ImportMarketDataJob"
  queue: "scheduled"
  description: "Imports market data daily at 5:00 PM EST (1 hour after market close)"
  args:
    mode: "full"
    clear_cache: false
