sync_market_data:
  cron: "0 17 * * 1-5" # 5:00 PM EST (1 hour after market close)
  class: "SyncMarketDataJob"
  queue: "scheduled"
  description: "Syncs market data daily at 5:00 PM EST (1 hour after market close)"
